### ISSUE TITLE
World not generate

### ISSUE THREAD

**Issue by SirMaxFox** [wode490390/TheEnd#13]
2021-01-12 00:13:43.194 [main] ERROR - Unable to generate level "the_end": java.lang.NullPointerException
	at cn.nukkit.Server.generateLevel(Server.java:2185)
	at cn.nukkit.Server.generateLevel(Server.java:2155)
	at cn.nukkit.Server.generateLevel(Server.java:2151)
	at cn.wode490390.nukkit.theend.listener.PortalListener.moveToTheEnd(PortalListener.java:159)
	at cn.wode490390.nukkit.theend.listener.PortalListener.onPlayerMove(PortalListener.java:72)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:28)
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:60)
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:577)
	at cn.nukkit.Player.processMovement(Player.java:1627)
	at cn.nukkit.Player.onUpdate(Player.java:1824)
	at cn.nukkit.level.Level.doTick(Level.java:942)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1279)
	at cn.nukkit.Server.tick(Server.java:1361)
	at cn.nukkit.Server.tickProcessor(Server.java:1125)
	at cn.nukkit.Server.start(Server.java:1085)
	at cn.nukkit.Server.<init>(Server.java:762)
	at cn.nukkit.Nukkit.main(Nukkit.java:120)

**Comment by Munz1211** [comment]
same error, cannot generate.
