### ISSUE TITLE
Neither overworld nor nether given

### ISSUE THREAD

**Issue by MasterLuke117** [wode490390/TheEnd#3]
thank you for creating this plugin, the kids love it!

heres an error that pops up, looks like maybe a player is trying to use a nether portal in the end?

```
2020-02-06 16:28:10.760 [main] ERROR - Could not tick level "the_end": java.lang.IllegalArgumentException: Neither overworld nor nether given!
	at cn.nukkit.level.EnumLevel.moveToNether(EnumLevel.java:68)
	at cn.nukkit.entity.Entity.entityBaseTick(Entity.java:1280)
	at cn.nukkit.entity.item.EntityItem.onUpdate(EntityItem.java:166)
	at cn.nukkit.level.Level.doTick(Level.java:821)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1055)
	at cn.nukkit.Server.tick(Server.java:1137)
	at cn.nukkit.Server.tickProcessor(Server.java:905)
	at cn.nukkit.Server.start(Server.java:882)
	at cn.nukkit.Server.<init>(Server.java:567)
	at cn.nukkit.Nukkit.main(Nukkit.java:112)
```

thanks!!!

Luke

**Comment by wode490390** [comment]
Fixed in https://github.com/wode490390/TheEnd/commit/d1c27a52017f6cbe49ac49625f6851658051bb04
